spring:
  config:
    import: local.properties
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: dev.properties

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true